apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-app-deployment
  labels:
    app: flask
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask
          image: frodan/dev_ops:latest
          ports:
            - containerPort: 8000
          env:
            - name: USER_LOGIN
              value: "change_me"
            - name: USER_PASS
              value: "change_me"

