name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      USER_LOGIN: ${{ secrets.USER_LOGIN }}
      USER_PASS: ${{ secrets.USER_PASS }}
    steps:
    - uses: actions/checkout@v2
    - run: python3 -m venv .
    - run: pip install -r app_python/requirements.txt
    - run: python -m unittest app_python/test/test_main.py

  
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      -
        name: checout
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: build and publish
        run: docker build . --file app_python/Dockerfile --tag dev_ops:latest && docker push frodan/dev_ops:latest

