name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      USER_LOGIN: ${{ secrets.USER_LOGIN }}
      USER_PASS: ${{ secrets.USER_PASS }}
    steps:
    - uses: actions/checkout@v2
    - run: python3 -m venv .
    - run: pip install -r app_python/requirements.txt
    - run: python -m unittest app_python/test/test_main.py


  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file app_python/Dockerfile --tag DevOps_flask:$(date +%s)
  
  #publish:
  #  runs-on: ubuntu-latest
  #  steps:
  #  - name: docker
    
